AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'thunderval'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-secure-baseline-tv'
VM_USERNAME: 'cwoodland'
ACCOUNT_NAME: 'replace me in repo secrets'
CICD_AGENT_TYPE: 'github'
CREATE_REDIS_RESOURCE: true
REDIS_TIER: 'Enterprise_E10'